services:
  - type: web
    name: climate-control
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 4 --timeout 120 cloud_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
